# Generated by Django 5.2.2 on 2025-06-18 07:58

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialCustomer',
            fields=[
                ('potential_customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='潛在客戶編號')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('country', models.CharField(choices=[('USA', '美國'), ('TAIWAN', '台灣'), ('JAPAN', '日本'), ('DENMARK', '丹麥'), ('GERMANY', '德國'), ('SWEDEN', '瑞典'), ('CANADA', '加拿大'), ('SWITZERLAND', '瑞士'), ('ITALY', '義大利'), ('FRANCE', '法國')], max_length=30, verbose_name='國家')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='公司地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='連絡電話')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('website', models.URLField(blank=True, verbose_name='公司網址')),
                ('currency', models.CharField(choices=[('NTD', '新台幣'), ('USD', '美金'), ('EUR', '歐元'), ('JPY', '日幣')], max_length=5, verbose_name='交易幣別')),
                ('status', models.CharField(choices=[('uncontacted', '未聯絡'), ('contacted', '開發中'), ('deal', '已成交'), ('refused', '拒絕往來')], default='uncontacted', max_length=50, verbose_name='狀態')),
                ('company_type', models.CharField(choices=[('resale', '貿易轉售'), ('die_maker', '模具設計/製造'), ('stamping', '金屬沖壓'), ('injection', '塑膠射出'), ('misc', '其他')], max_length=30, verbose_name='公司類型')),
                ('industries', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('aerospace', '航太'), ('automotive', '汽車模具'), ('electronic', '電子'), ('semi-conductor', '半導體'), ('medical', '醫療'), ('automation', '自動化'), ('architectural', '建築'), ('food', '食品'), ('others', '其他')], max_length=100, verbose_name='產業別')),
                ('required_products', models.CharField(blank=True, max_length=200, verbose_name='需求品項')),
                ('rank', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=5, verbose_name='客戶評級')),
                ('source', models.CharField(blank=True, choices=[('website', '博威官網'), ('event', '展覽開發'), ('search', '搜尋引擎'), ('introduced', '客戶轉介')], max_length=30, verbose_name='客戶來源')),
                ('is_visitable', models.BooleanField(default=False, verbose_name='安排可拜訪')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('sales_incharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='業務人員')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='聯絡人')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='職稱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('potential_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.potentialcustomer', verbose_name='關聯客戶')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30, verbose_name='主旨')),
                ('log', models.TextField(blank=True, verbose_name='聯絡內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='聯絡日期')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='業務人員')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.contacts', verbose_name='聯絡人')),
                ('potential_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.potentialcustomer', verbose_name='關聯客戶')),
            ],
        ),
    ]
