# Generated by Django 5.2.2 on 2025-06-26 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialcustomer',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='重點關注'),
        ),
        migrations.AlterField(
            model_name='contactlogs',
            name='potential_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='leads.potentialcustomer', verbose_name='關聯客戶'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='potential_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='leads.potentialcustomer', verbose_name='關聯客戶'),
        ),
    ]
