# Generated by Django 5.2.2 on 2025-06-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_potentialcustomer_is_pinned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlogs',
            old_name='log',
            new_name='content',
        ),
    ]
