# Generated by Django 5.2.2 on 2025-06-27 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0003_rename_log_contactlogs_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bwp_no', models.CharField(max_length=20, unique=True, verbose_name='博威報價單號')),
                ('enquiry_no', models.CharField(blank=True, max_length=20, verbose_name='客戶報價單')),
                ('status', models.CharField(choices=[('untracked', '未追蹤'), ('tracking', '追蹤中'), ('success', '已成交'), ('lost', '已失去')], default='untracked', max_length=20, verbose_name='追蹤狀態')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='重點追蹤')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('potential_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.potentialcustomer', verbose_name='客戶')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=30, verbose_name='產品名稱')),
                ('item_spec', models.CharField(blank=True, max_length=30, verbose_name='產品規格')),
                ('material', models.CharField(blank=True, max_length=30, verbose_name='材質')),
                ('unit_price', models.FloatField(blank=True, verbose_name='單價')),
                ('exchange_rate', models.FloatField(blank=True, verbose_name='匯率')),
                ('quantity', models.IntegerField(blank=True, verbose_name='數量')),
                ('cost', models.FloatField(blank=True, verbose_name='進價')),
                ('cost_rate', models.FloatField(blank=True, verbose_name='進價匯率')),
                ('supplier', models.CharField(blank=True, max_length=30, verbose_name='供應商')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lead_enquiries.enquiry', verbose_name='報價單')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('content', models.TextField(blank=True, verbose_name='內容')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立人')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='lead_enquiries.enquiry', verbose_name='報價單')),
            ],
        ),
    ]
