# Generated by Django 5.2.2 on 2025-06-27 06:28

import django.db.models.deletion
import lead_enquiries.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_enquiries', '0001_initial'),
        ('leads', '0003_rename_log_contactlogs_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='potential_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='leads.potentialcustomer', verbose_name='客戶'),
        ),
        migrations.CreateModel(
            name='EnquiryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=lead_enquiries.models.enquiry_attachment_path, verbose_name='檔案')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='檔案描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lead_enquiries.enquiry', verbose_name='報價單')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '報價單附件',
                'verbose_name_plural': '報價單附件',
            },
        ),
    ]
