# Generated by Django 5.2.2 on 2025-06-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardGoal',
            fields=[
                ('period', models.CharField(choices=[('monthly', '本月目標'), ('quarterly', '本季目標'), ('yearly', '年度目標')], max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='統計週期')),
                ('new_customer_target', models.PositiveIntegerField(default=10, verbose_name='新增潛在客戶數目標')),
                ('new_enquiry_target', models.PositiveIntegerField(default=20, verbose_name='新增報價數目標')),
                ('enquiry_amount_target', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12, verbose_name='新增報價總金額目標')),
                ('success_amount_target', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='成交總金額目標')),
            ],
            options={
                'verbose_name': '儀表板目標設定',
                'verbose_name_plural': '儀表板目標設定',
            },
        ),
    ]
